import java.util.*;

public class Tables {
	private Map <String, Student> studentsTable;
	private Map <String, Course> coursesTable;
	private Map <String, Grade> gradesTable;
	
	public Tables(){
		studentsTable = new HashMap<String, Student>();
		coursesTable = new HashMap<String, Course>();
		gradesTable = new HashMap<String, Grade>();
	}
	
		
	public void insertStudent (Student s){
		studentsTable.put(s.getSid(), s);
	}
	
	public void insertCourse (Course c){
		coursesTable.put(c.getCid(), c);
	}
	
	public void insertGrade (Grade g){
		String key = g.getSid() + g.getSid() + g.getYear() + g.getSemester(); //the key is generated by SID, CID, Year and Semester, as a Student may have taken a given course many times (different semester/year)
		gradesTable.put(key, g);
	}
	
	
	//List the Name, ID, and grade of every student who has taken the Databases course.
	public String output(){
		
		String CID = "";
		String output = "  /------Name------/---ID---/---Grade---/\n";
		
		for (Map.Entry <String, Course> entry: coursesTable.entrySet()) {
			if (entry.getValue().getCName().equals("Databases")){
				CID = entry.getKey();
			}
		}
		
		for (Map.Entry <String, Grade> entry: gradesTable.entrySet()) {
			if (entry.getValue().getCid().equals(CID)){
				String grade = entry.getValue().getGrade();
				String id = entry.getValue().getSid();
				String name = studentsTable.get(id).getSName();
				output += "  / " + name + "  /  " + id + "  /  " + grade + "\n" ; 
			}
		}
	 return output;
	}
	
		
}

